# Change these first
owner: unikino-gegenlicht
repo: status-monitor

assigninees:
  - dr4hcu5-jan

sites:
  - name: Website
    url: https://gegenlicht.net
    maxResponseTime: 5000

  - name: Website Analytics
    url: https://plausible.gegenlicht.net
    icon: https://plausible.io/assets/images/icon/favicon-32x32.png

  - name: Identity and Access Management
    url: https://accounts.gegenlicht.net/-/health/ready/
    icon: https://docs.goauthentik.io/img/icon.png

  - name: Survey and Form Tool
    url: https://forms.gegenlicht.net
    icon: https://www.limesurvey.org/templates/limesurvey/favicon.ico

  - name: Knowledge Base
    url: https://wiki.gegenlicht.net
    icon: https://www.dokuwiki.org/lib/tpl/dokuwiki/images/logo.png
    maxRedirects: 10

  - name: Appointment Planner
    url: https://terminplaner.gegenlicht.net
    icon: https://rallly.co/favicon.ico

  - name: Ticketing
    url: https://tickets.gegenlicht.net
    icon: https://static.pretix.space/static/pretixbase/img/icons/favicon-16x16.ce949675f6e2.png

  - name: Mailing List Management
    url: https://lists.gegenlicht.net

  - name: E-Mail Groupware
    url: https://portal.gegenlicht.net
    icon: https://www.group-office.com/favicon.ico

  - name: IMAP
    check: "tcp-ping"
    url: mail.gegenlicht.net
    port: 143

  - name: IMAP (TLS/SSL)
    check: "tcp-ping"
    url: mail.gegenlicht.net
    port: 993

  - name: SMTP
    check: "tcp-ping"
    url: mail.gegenlicht.net
    port: 25

  - name: SMTP (explicit TLS)
    check: "tcp-ping"
    url: mail.gegenlicht.net
    port: 587

  - name: SMTP (implicit SSL)
    check: "tcp-ping"
    url: mail.gegenlicht.net
    port: 465

status-website:
  cname: status.gegenlicht.net
  logoUrl: https://raw.githubusercontent.com/unikino-gegenlicht/status-monitor/refs/heads/master/assets/icon.svg
  name: Unikino GEGENLICHT Status
  introTitle: "Unikino GEGENLICHT"
  introMessage: |
    Dein studentisches Kino an der Carl von Ossietzky Universität Oldenburg.

    Hier findest du das aktuelle monitoring unserer Services die wir intern und
    extern anbieten. Sollte etwas mal nicht richtig laufen oder Wartungsarbeiten
    stattfinden, wird dies hier angezeigt. Sollte ein Service ausnahmsweise 
    nicht funktionieren und es wir hier nicht angezeigt, dann sage uns bitte
    bescheid und wir kümmern uns darum.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
