# Change these first
owner: unikino-gegenlicht
repo: status-monitor

assigninees:
  - dr4hcu5-jan

sites:
  - name: Website
    url: https://gegenlicht.net
    maxResponseTime: 5000

  - name: Identity and Access Management
    url: https://accounts.gegenlicht.net/-/health/ready/
    icon: https://docs.goauthentik.io/img/icon.png

  - name: Knowledge Base
    url: https://wiki.gegenlicht.net
    icon: https://www.dokuwiki.org/lib/tpl/dokuwiki/images/logo.png

  - name: Appointment Planner
    url: https://terminplaner.gegenlicht.net
    icon: https://rallly.co/favicon.ico

  - name: E-Mail Groupware
    url: https://portal.gegenlicht.net
    icon: https://www.group-office.com/favicon.ico

  - name: Ticketing
    url: https://tickets.gegenlicht.net
    icon: https://static.pretix.space/static/pretixbase/img/icons/favicon-16x16.ce949675f6e2.png

  - name: Mailing List Management
    url: https://lists.gegenlicht.net

  - name: IMAP
    check: "tcp-ping"
    url: mail.gegenlicht.net
    port: 143

  - name: IMAP (TLS/SSL)
    check: "tcp-ping"
    url: mail.gegenlicht.net
    port: 993

  - name: SMTP
    check: "tcp-ping"
    url: mail.gegenlicht.net
    port: 25

  - name: SMTP (explicit TLS)
    check: "tcp-ping"
    url: mail.gegenlicht.net
    port: 587

  - name: SMTP (implicit SSL)
    check: "tcp-ping"
    url: mail.gegenlicht.net
    port: 465


status-website:
  cname: status.gegenlicht.net
  logoUrl: https://raw.githubusercontent.com/unikino-gegenlicht/status-monitor/refs/heads/master/assets/icon.svg
  name: Unikino GEGENLICHT Status
  introTitle: "Unikino GEGENLICHT"
  introMessage: "Dein studentisches Kino"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
